server:
  port: 1001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Zara2025!
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml